Implemented CRUD API by Vladyslav Yarmolenko
parzhitsky/express-try pull request #1
Opened 2021-02-27 21:16 UTC by VladyslavYarmolenko

2021-02-28 12:23 UTC, parzhitsky commented
@VladyslavYarmolenko Молодец, справился первее всех! 🥇 

Сделай, пожалуйста, некоторые исправления, чтобы код был более аккуратным:

- [ ] удали пустые файлы `node` и `express-try@1.0.0`, – это наверное неубранные остатки каких-то команд;
- [ ] отмени изменения в `package*` файлах: [убери `^` символы в `package.json`](https://stackoverflow.com/a/22345808/4554883) и [верни содержимое `package-lock.json`](https://stackoverflow.com/a/44210813/4554883) (по ссылкам объяснение почему так надо сделать);

2021-02-28 12:33 UTC, VladyslavYarmolenko commented
Добрый день, ок . )Ближе к вечеру пофиксю и запушу)

нд, 28 лют. 2021, 14:23 користувач Dima Parzhitsky <notifications@github.com>
пише:

> @VladyslavYarmolenko <https://github.com/VladyslavYarmolenko> Молодец,
> справился первее всех! 🥇
>
> Сделай, пожалуйста, некоторые исправления, чтобы код был более аккуратным:
>
>    - удали пустые файлы node и express-try@1.0.0, – это наверное
>    неубранные остатки каких-то команд;
>    - отмени изменения в package* файлах: убери ^ символы в package.json
>    <https://stackoverflow.com/a/22345808/4554883> и верни содержимое
>    package-lock.json <https://stackoverflow.com/a/44210813/4554883> (по
>    ссылкам объяснение почему так надо сделать);
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/parzhitsky/express-try/pull/1#issuecomment-787443930>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANNV3DDS7QVPPJ6MQ7XQ2UTTBIYTXANCNFSM4YKKEIOA>
> .
>

2021-02-28 13:31 UTC, parzhitsky requested changes
@VladyslavYarmolenko Молодец, справился первее всех! 🥇 

Сделай, пожалуйста, некоторые исправления, чтобы код был более аккуратным:

- [ ] удали пустые файлы `node` и `express-try@1.0.0`, – это наверное неубранные остатки каких-то команд;
- [ ] отмени изменения в `package*` файлах: [убери `^` символы в `package.json`](https://stackoverflow.com/a/22345808/4554883) и [верни содержимое `package-lock.json`](https://stackoverflow.com/a/44210813/4554883) (по ссылкам объяснение почему так надо сделать);

2021-02-28 13:31 UTC, parzhitsky commented on src/router/index.js
> +	router.route("/users/:id")
> Этот путь уже создан

То же самое ([строка 57](https://github.com/parzhitsky/express-try/pull/1/files#diff-3210ca9ed615e6f0fc1743fc09be3c86bc38178dcc050e5a41ff7982d15875b7R57)).

2021-02-28 13:31 UTC, parzhitsky commented on src/router/index.js
> +	router.route("/users/:id")
> Этот путь уже создан

То же самое ([строка 57](https://github.com/parzhitsky/express-try/pull/1/files#diff-3210ca9ed615e6f0fc1743fc09be3c86bc38178dcc050e5a41ff7982d15875b7R57)).

2021-02-28 13:31 UTC, parzhitsky commented on src/router/index.js
> +			if(users[i].id === user.id){
И ещё, мы уже нашли пользователя по ID ([строка 71](https://github.com/parzhitsky/express-try/pull/1/files#diff-3210ca9ed615e6f0fc1743fc09be3c86bc38178dcc050e5a41ff7982d15875b7R71)), нам не надо его снова искать

2021-02-28 13:31 UTC, parzhitsky commented on src/router/index.js
> +			}
> вынести в отдельную функцию в отдельный файл

То же самое.

2021-02-28 13:31 UTC, parzhitsky commented on src/router/index.js
> +			return res.status(200).json(removedUser);
Если пользователь не найден, должна быть ошибка 404

2021-03-01 12:35 UTC, closed without merging

2021-03-01 12:57 UTC, VladyslavYarmolenko commented
Thanks!

пн, 1 бер. 2021, 14:35 користувач Dima Parzhitsky <notifications@github.com>
пише:

> Closed #1 <https://github.com/parzhitsky/express-try/pull/1>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/parzhitsky/express-try/pull/1#event-4389288935>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANNV3DCP2BXAQPSJM24ANB3TBOCZBANCNFSM4YKKEIOA>
> .
>